# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Emotions' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Emotions
pod 'BetterSegmentedControl', '~> 2.0'
pod 'PanModal'
pod 'lottie-ios'
pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'TransitionButton'
pod 'BulletinBoard'
end
